#!/bin/bash
set -e

# ---------------------------------------------------------------------------
# Canonical env source: .env.testnet at the repo root.
# All network values are read from / written to this file so that the
# frontend, backend, and scripts all reference the same contract ID.
# ---------------------------------------------------------------------------
ENV_FILE="${ENV_FILE:-.env.testnet}"

# Load existing env if present (allows overriding defaults)
if [ -f "$ENV_FILE" ]; then
  # shellcheck disable=SC1090
  set -a; source "$ENV_FILE"; set +a
fi

STELLAR_NETWORK="${STELLAR_NETWORK:-testnet}"
STELLAR_HORIZON_URL="${STELLAR_HORIZON_URL:-https://horizon-testnet.stellar.org}"
STELLAR_SOROBAN_RPC_URL="${STELLAR_SOROBAN_RPC_URL:-https://soroban-testnet.stellar.org}"

echo "Deploying Token Factory to Stellar ${STELLAR_NETWORK}..."

# Check if admin identity exists
if ! soroban keys show admin &> /dev/null; then
    echo "Error: Admin identity not found. Run setup-soroban.sh first."
    exit 1
fi

# Check if treasury identity exists
if ! soroban keys show treasury &> /dev/null; then
    echo "Creating treasury identity..."
    soroban keys generate --global treasury
fi

# Get addresses
ADMIN_ADDRESS=$(soroban keys address admin)
TREASURY_ADDRESS=$(soroban keys address treasury)

echo "Admin address:    $ADMIN_ADDRESS"
echo "Treasury address: $TREASURY_ADDRESS"

# Deploy contract
echo "Deploying contract..."
CONTRACT_ID=$(soroban contract deploy \
  --wasm contracts/token-factory/target/wasm32-unknown-unknown/release/token_factory.wasm \
  --network "$STELLAR_NETWORK" \
  --source admin)

echo "Contract deployed!"
echo "Contract ID: $CONTRACT_ID"

# Initialize factory
echo "Initializing factory..."
soroban contract invoke \
  --id "$CONTRACT_ID" \
  --network "$STELLAR_NETWORK" \
  --source admin \
  -- initialize \
  --admin "$ADMIN_ADDRESS" \
  --treasury "$TREASURY_ADDRESS" \
  --base_fee 70000000 \
  --metadata_fee 30000000

echo "Factory initialized!"

# ---------------------------------------------------------------------------
# Write canonical env file so all consumers (frontend, backend, scripts)
# reference the same contract ID and network values.
# ---------------------------------------------------------------------------
cat > "$ENV_FILE" <<EOF
# Auto-generated by deploy-testnet.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# This is the canonical source of truth for network and contract configuration.
# Frontend: copy VITE_* vars to frontend/.env
# Backend:  copy remaining vars to backend/.env

STELLAR_NETWORK=${STELLAR_NETWORK}
STELLAR_HORIZON_URL=${STELLAR_HORIZON_URL}
STELLAR_SOROBAN_RPC_URL=${STELLAR_SOROBAN_RPC_URL}
FACTORY_CONTRACT_ID=${CONTRACT_ID}

# Frontend equivalents (Vite requires VITE_ prefix)
VITE_NETWORK=${STELLAR_NETWORK}
VITE_FACTORY_CONTRACT_ID=${CONTRACT_ID}
EOF

echo "Canonical env written to $ENV_FILE"

# Also update frontend/.env if it exists
if [ -f "frontend/.env" ]; then
  sed -i "s|^VITE_FACTORY_CONTRACT_ID=.*|VITE_FACTORY_CONTRACT_ID=${CONTRACT_ID}|" frontend/.env
  sed -i "s|^VITE_NETWORK=.*|VITE_NETWORK=${STELLAR_NETWORK}|" frontend/.env
  echo "frontend/.env updated"
fi

# Save legacy deployment info for verify-deployment.sh
cat > deployment-testnet.json <<EOF
{
  "network": "${STELLAR_NETWORK}",
  "contractId": "${CONTRACT_ID}",
  "admin": "${ADMIN_ADDRESS}",
  "treasury": "${TREASURY_ADDRESS}",
  "baseFee": 70000000,
  "metadataFee": 30000000,
  "deployedAt": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
EOF

echo "Deployment info saved to deployment-testnet.json"

# Smoke test
echo "Testing deployment..."
soroban contract invoke \
  --id "$CONTRACT_ID" \
  --network "$STELLAR_NETWORK" \
  --source admin \
  -- get_state

echo "Deployment complete!"
